name: aws-iam-role-starter
component: aws-iam-role
org: serverlessinc
description: Deploys an AWS IAM role
keywords: aws, serverless, iam, permissions
repo: https://github.com/serverless-components/aws-iam-role
license: MIT

inputs:
  service: lambda.amazonaws.com
  policy:
    - Effect: Allow
      Action:
        - sts:AssumeRole
      Resource: '*'
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: '*'
